
name: Java CI with Maven

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  build:

    runs-on: runner_rja

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0 
    - name: docker build
      run: |
        docker build -t devpprojectrajesh.azurecr.io/git-actions:latest .
    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        registry: devpprojectrajesh.azurecr.io
        username: ${ secrets.REPO_USER }
        password: ${ secrets.REPO_TOKEN }
      
   
