name: Java CI with Maven

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: testing reusable workflow
      uses: ./.github/workflows/maven.yml
